### ISSUE TITLE
Database creation of boardnotes table

### ISSUE THREAD

**Issue by Tupax** [ThomasTJdev/Boardnotes#1]
What attributes does that table have to have? So I can create it

Application version: 1.2.4
PHP version: 7.2.7
Database driver: mysql
Database version: 10.1.31-MariaDB-cll-lve 

> 
Internal Error: SQL Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXdatabaseXXX.boardnotes' doesn't exist

**Comment by Tupax** [comment]
Ok this att..

$client->execute('createTask', ['title' => $title, 'description' => $description, 'project_id' => $project_id, 'column_id' => $column_id, 'category_id' => $category_id, 'svimlane_id' => $svimlane_id]);

**Comment by ThomasTJdev** [comment]
@Tupax: Thank you for posting the answer. I do not maintain this repo anymore - I have updated the README.md with that information.

**Comment by aljawaid** [comment]
> @ThomasTJdev: Thank you for posting the answer. I do not maintain this repo anymore - I have updated the README.md with that information.

Hello, can you pass it on? I could try to revive it.  The screenshot looks very promising and it would be sad to see your efforts wasted.

**Comment by ThomasTJdev** [comment]
Hi @aljawaid 

Yeah, of course. I have invited you to the repo. I will give you full access. Ping me when you have accepted.

**Comment by aljawaid** [comment]
@ThomasTJdev hello, thanks, I have accepted....

Am I right that this plugin is like post-it sticky notes...? A brief developer rudown would be good in case I need to know anything

**Comment by ThomasTJdev** [comment]
Great, you have access rights. If you're going to use it, then I can transfer ownership as well.

It's so long time since I did the code. I can't give any details anymore, sorry.

**Comment by aljawaid** [comment]
Yes please transfer ownership if you do not plan to use it.  I will go through the code and also create a release so that it can be submitted to the extensions directory

**Comment by ThomasTJdev** [comment]
Done - and thanks.

I got a couple of more plugins if you are interested: https://github.com/ThomasTJdev?tab=repositories&q=kanboard&type=&language=&sort=

**Comment by aljawaid** [comment]
> Done - and thanks.
> 
> I got a couple of more plugins if you are interested: https://github.com/ThomasTJdev?tab=repositories&q=kanboard&type=&language=&sort=

I will go through them later tonight.... even if I dont use them personally, I can always list them in the directory for others but let's see

**Comment by ThomasTJdev** [comment]
Just ping me. I'm in no need of them anymore, and will not be updating them anymore.
